# Generated by Django 5.2.5 on 2025-12-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_id', models.CharField(help_text='Jobber client ID (for deduplication)', max_length=64, unique=True)),
                ('jobber_client_id', models.CharField(blank=True, help_text="Jobber's client identifier", max_length=64)),
                ('name', models.CharField(help_text='Customer display name', max_length=255)),
                ('company_name', models.CharField(blank=True, help_text='Company name if business customer', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Primary email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=50)),
                ('billing_address_line1', models.CharField(blank=True, max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, max_length=255)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_state', models.CharField(blank=True, max_length=50)),
                ('billing_zip', models.CharField(blank=True, max_length=20)),
                ('service_address_line1', models.CharField(blank=True, max_length=255)),
                ('service_address_line2', models.CharField(blank=True, max_length=255)),
                ('service_city', models.CharField(blank=True, max_length=100)),
                ('service_state', models.CharField(blank=True, max_length=50)),
                ('service_zip', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True, help_text='Is this customer active?')),
                ('synced_at', models.DateTimeField(help_text='When this record was last synced from Jobber')),
                ('jobber_raw', models.JSONField(blank=True, help_text='Raw JSON response from Jobber API (for debugging)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='Forbes Lawn Spraying LLC entity', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_customers', to='django_ledger.entitymodel')),
                ('ledger_customer', models.ForeignKey(blank=True, help_text='Link to Django Ledger customer record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_customer', to='django_ledger.customermodel')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'forbes_lawn_customer',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['entity', 'name'], name='forbes_lawn_entity__2a838b_idx'), models.Index(fields=['entity', 'active'], name='forbes_lawn_entity__c4fe42_idx'), models.Index(fields=['jobber_id'], name='forbes_lawn_jobber__7bf21e_idx')],
            },
        ),
    ]
