# Generated by Django 5.2.5 on 2025-12-29 21:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('forbes_lawn_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_id', models.CharField(help_text='Jobber product/service ID (for deduplication)', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Service name (e.g., 'Fertilization Round 1')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of service')),
                ('category_name', models.CharField(blank=True, help_text="Jobber category (e.g., 'Fertilization', 'Weed Control')", max_length=255)),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default price for this service', max_digits=10)),
                ('taxable', models.BooleanField(default=True, help_text='Is this service subject to sales tax?')),
                ('active', models.BooleanField(default=True, help_text='Is this service actively offered?')),
                ('synced_at', models.DateTimeField(help_text='When this record was last synced from Jobber')),
                ('jobber_raw', models.JSONField(blank=True, help_text='Raw JSON response from Jobber API (for debugging)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='Forbes Lawn Spraying LLC entity', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_service_items', to='django_ledger.entitymodel')),
                ('ledger_item', models.ForeignKey(blank=True, help_text='Link to Django Ledger item record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_service_item', to='django_ledger.itemmodel')),
                ('revenue_account', models.ForeignKey(help_text='COA account for revenue (4024 Taxable or 4025 Non-Taxable)', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_service_items', to='django_ledger.chartofaccountmodel')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'db_table': 'forbes_lawn_service_item',
                'ordering': ['category_name', 'name'],
                'indexes': [models.Index(fields=['entity', 'name'], name='forbes_lawn_entity__fb30b4_idx'), models.Index(fields=['entity', 'active'], name='forbes_lawn_entity__566461_idx'), models.Index(fields=['entity', 'category_name'], name='forbes_lawn_entity__2e304e_idx'), models.Index(fields=['jobber_id'], name='forbes_lawn_jobber__c7b1d1_idx')],
            },
        ),
    ]
