# Generated by Django 5.2.5 on 2025-12-29 22:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0028_adminreports'),
        ('forbes_lawn_accounting', '0002_serviceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_invoice_id', models.CharField(help_text='Jobber invoice ID (for deduplication)', max_length=64, unique=True)),
                ('jobber_job_numbers', models.CharField(blank=True, help_text="Jobber job numbers (e.g., '1219, 1225')", max_length=255)),
                ('invoice_number', models.CharField(help_text="Visible invoice number (e.g., '492')", max_length=50)),
                ('invoice_date', models.DateField(help_text='Date invoice was issued')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items before tax', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoice-level discount', max_digits=10)),
                ('taxable_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of taxable line items', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax rate as decimal (e.g., 0.0865 for 8.65%)', max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sales tax amount', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount (subtotal - discount + tax)', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all payments received', max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance (total - amount_paid)', max_digits=10)),
                ('note_to_customer', models.TextField(blank=True, help_text='Customer-visible note on invoice')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not shown to customer)')),
                ('posted_to_ledger', models.BooleanField(default=False, help_text='Has this invoice been posted to the ledger?')),
                ('posted_at', models.DateTimeField(blank=True, help_text='When this invoice was posted to ledger', null=True)),
                ('synced_at', models.DateTimeField(help_text='When this record was last synced from Jobber')),
                ('jobber_raw', models.JSONField(blank=True, help_text='Raw JSON response from Jobber API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ar_journal_entry', models.ForeignKey(blank=True, help_text='Journal entry that posts AR + Revenue + Tax', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forbes_lawn_accounting_invoices_ar', to='django_ledger.journalentrymodel')),
                ('customer', models.ForeignKey(help_text='Customer being invoiced', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='forbes_lawn_accounting.customer')),
                ('entity', models.ForeignKey(help_text='Forbes Lawn Spraying LLC entity', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_accounting_invoices', to='django_ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'forbes_lawn_invoice',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_line_id', models.CharField(help_text='Jobber line item ID', max_length=64)),
                ('line_number', models.PositiveIntegerField(help_text='Line order on invoice')),
                ('service_date', models.DateField(blank=True, help_text='Date service was performed', null=True)),
                ('description', models.CharField(help_text='Service description', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity of service', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Line total (quantity × rate)', max_digits=10)),
                ('taxable', models.BooleanField(default=True, help_text='Is this line subject to sales tax?')),
                ('invoice', models.ForeignKey(help_text='Invoice this line belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forbes_lawn_accounting.invoice')),
                ('service_item', models.ForeignKey(blank=True, help_text='Service performed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='forbes_lawn_accounting.serviceitem')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'forbes_lawn_invoice_line',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_payment_id', models.CharField(help_text='Jobber payment ID (for deduplication)', max_length=64, unique=True)),
                ('payment_date', models.DateField(help_text='Date payment was received')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Credit Card'), ('ACH', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Check number, last 4 of card, etc.', max_length=100)),
                ('jobber_paid_with', models.CharField(blank=True, help_text="Jobber payment method (e.g., 'visa', 'cash')", max_length=50)),
                ('jobber_paid_through', models.CharField(blank=True, help_text="Jobber payment processor (e.g., 'jobber_payments')", max_length=50)),
                ('posted_to_ledger', models.BooleanField(default=False, help_text='Has this payment been posted to the ledger?')),
                ('posted_at', models.DateTimeField(blank=True, help_text='When this payment was posted to ledger', null=True)),
                ('cleared', models.BooleanField(default=False, help_text='Has this payment cleared the bank?')),
                ('cleared_date', models.DateField(blank=True, help_text='Date payment cleared the bank', null=True)),
                ('synced_at', models.DateTimeField(help_text='When this record was last synced from Jobber')),
                ('jobber_raw', models.JSONField(blank=True, help_text='Raw JSON response from Jobber API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='forbes_lawn_accounting.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry that posts payment to Payments to Deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forbes_lawn_accounting_invoice_payments', to='django_ledger.journalentrymodel')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'db_table': 'forbes_lawn_invoice_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['entity', 'invoice_date'], name='forbes_lawn_entity__2f051c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['entity', 'customer', 'status'], name='forbes_lawn_entity__9be912_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['entity', 'status', 'balance_due'], name='forbes_lawn_entity__f3bb71_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['jobber_invoice_id'], name='forbes_lawn_jobber__adad17_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='forbes_lawn_invoice_76b124_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'line_number'], name='forbes_lawn_invoice_c2f87e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceline',
            unique_together={('invoice', 'jobber_line_id')},
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['invoice', 'payment_date'], name='forbes_lawn_invoice_ac3c68_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['payment_date'], name='forbes_lawn_payment_81731c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['cleared', 'cleared_date'], name='forbes_lawn_cleared_81e504_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['jobber_payment_id'], name='forbes_lawn_jobber__97228f_idx'),
        ),
    ]
