# Generated by Django 5.2.5 on 2025-12-30 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0028_adminreports'),
        ('forbes_lawn_accounting', '0003_invoice_invoiceline_invoicepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='revenue_account',
            field=models.ForeignKey(help_text='COA account for revenue (4024 Taxable or 4025 Non-Taxable)', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_service_items', to='django_ledger.accountmodel'),
        ),
    ]
