# Generated by Django 5.2.5 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbes_lawn_accounting', '0004_alter_serviceitem_revenue_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name if business customer', max_length=255, null=True),
        ),
    ]
