# Generated by Django 5.2.5 on 2026-01-01 02:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       
        ('forbes_lawn_accounting', '0005_alter_customer_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='First day of the month (e.g., 2026-01-01 for January 2026)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice revenue for the month', max_digits=10)),
                ('taxable_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue from taxable services', max_digits=10)),
                ('non_taxable_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Revenue from non-taxable services (mowing, aeration, etc.)', max_digits=10)),
                ('tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax from Jobber invoices - SOURCE OF TRUTH', max_digits=10)),
                ('filed', models.BooleanField(default=False, help_text="Has this month's tax been filed with Kansas DOR?")),
                ('filed_date', models.DateField(blank=True, help_text='Date filed with Kansas DOR', null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to Kansas DOR', max_digits=10, null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date payment was made to Kansas DOR', null=True)),
                ('payment_confirmation', models.CharField(blank=True, help_text='Confirmation number from Kansas DOR', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Filing notes, adjustments, etc.')),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='When amounts were last recalculated from invoices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='Forbes Lawn Spraying LLC entity', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_tax_summaries', to='django_ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Sales Tax Summary',
                'verbose_name_plural': 'Sales Tax Summaries',
                'db_table': 'forbes_lawn_sales_tax_summary',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['entity', 'month'], name='forbes_lawn_entity__0cc31d_idx'), models.Index(fields=['filed', 'month'], name='forbes_lawn_filed_9cf6b7_idx')],
                'unique_together': {('entity', 'month')},
            },
        ),
    ]
