# Generated by Django 5.2.5 on 2026-01-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0028_adminreports'),
        ('forbes_lawn_accounting', '0006_salestaxsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, help_text="Optional property name (e.g., 'Main House', 'Rental Property #1')", max_length=255)),
                ('street1', models.CharField(help_text='Street address', max_length=255)),
                ('street2', models.CharField(blank=True, help_text='Apt, Unit, Suite', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Kansas', max_length=50)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('lawn_square_footage', models.DecimalField(blank=True, decimal_places=2, help_text='Total lawn area in square feet', max_digits=10, null=True)),
                ('tax_name', models.CharField(blank=True, help_text="Jobber tax name (e.g., 'KS-Johnson-Overland Park')", max_length=255)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Tax rate as percentage (e.g., 9.35 for 9.35%)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Property-specific notes (gate code, dog, locked gate, etc.)')),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the customer's primary/default property?")),
                ('active', models.BooleanField(default=True, help_text='Is this property actively serviced?')),
                ('jobber_property_id', models.CharField(blank=True, help_text='Jobber property ID (for deduplication)', max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this record was last synced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer who owns/manages this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='forbes_lawn_accounting.customer')),
                ('entity', models.ForeignKey(help_text='Forbes Lawn Spraying LLC entity', on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_properties', to='django_ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'forbes_lawn_property',
                'ordering': ['customer__name', '-is_primary', 'street1'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Property/location where service was performed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='forbes_lawn_accounting.property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['customer', 'is_primary'], name='forbes_lawn_custome_c9376c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['entity', 'active'], name='forbes_lawn_entity__9bf7e7_idx'),
        ),
    ]
