# Generated by Django 5.2.5 on 2025-10-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Which area does this task support?', max_length=100)),
                ('priority', models.CharField(choices=[('high', 'High'), ('med', 'Medium'), ('low', 'Low')], default='med', max_length=4)),
                ('status', models.CharField(choices=[('idea', 'Idea / backlog'), ('doing', 'In progress'), ('wait', 'Waiting on something'), ('done', 'Done')], default='idea', max_length=5)),
                ('owner', models.CharField(blank=True, help_text="Who's on this?", max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'due_date', 'status', '-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='BusinessTask',
        ),
        migrations.AlterModelOptions(
            name='businesstask',
            options={'verbose_name': 'Business Task', 'verbose_name_plural': 'Business Tasks'},
        ),
    ]
