# Generated by Django 5.2.5 on 2025-10-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_systemtask_rename_task_businesstask_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstask',
            options={'ordering': ['-priority', 'due_date', 'status', '-created_at'], 'verbose_name': 'Business Task', 'verbose_name_plural': 'Business Tasks'},
        ),
        migrations.AlterModelOptions(
            name='systemtask',
            options={'ordering': ['-priority', 'due_date', 'status', '-created_at'], 'verbose_name': 'System Task', 'verbose_name_plural': 'System Tasks'},
        ),
        migrations.RemoveField(
            model_name='businesstask',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='systemtask',
            name='category',
        ),
        migrations.AddField(
            model_name='businesstask',
            name='owner',
            field=models.CharField(blank=True, help_text="Who's on this? (Me, Husband, Gallery Contact, Printer, etc.)", max_length=100),
        ),
        migrations.AddField(
            model_name='businesstask',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('med', 'Medium'), ('low', 'Low')], default='med', max_length=4),
        ),
        migrations.AddField(
            model_name='businesstask',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea / backlog'), ('doing', 'In progress'), ('wait', 'Waiting / on order'), ('done', 'Done')], default='idea', max_length=5),
        ),
        migrations.AlterField(
            model_name='systemtask',
            name='owner',
            field=models.CharField(blank=True, help_text="Who's on this? (Me, Harold, Son, Gallery, etc.)", max_length=100),
        ),
        migrations.AlterField(
            model_name='systemtask',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea / backlog'), ('doing', 'In progress'), ('wait', 'Waiting / blocked'), ('done', 'Done')], default='idea', max_length=5),
        ),
    ]
