# Generated by Django 5.2.7 on 2025-10-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminReports',
        ),
    ]
