# Generated by Django 5.2.5 on 2025-10-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_delete_adminreports'),
        ('django_ledger', '0028_adminreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_method', models.CharField(choices=[('PCT', 'Percent'), ('AMT', 'Fixed Amount')], default='AMT', max_length=3)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='django_ledger.billmodel')),
                ('cash_account_override', models.ForeignKey(blank=True, help_text='Override cash/bank account when marking bill paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_cash_accounts', to='django_ledger.accountmodel')),
                ('default_expense_acct', models.ForeignKey(blank=True, help_text='Expense account to use for lines without a specific account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_default_expense_accounts', to='django_ledger.accountmodel')),
                ('discount_account', models.ForeignKey(blank=True, help_text='Contra-expense or purchase discount account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_discount_accounts', to='django_ledger.accountmodel')),
            ],
        ),
    ]
