# Generated by Django 5.2.5 on 2025-10-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillExtras',
        ),
    ]
