# Generated by Django 5.2.5 on 2025-11-04 15:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0027_alter_accountmodel_role_alter_receiptmodel_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='django_ledger.entitymodel')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='PendingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=160)),
                ('po_or_bill_ref', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_pending_receipts', to='django_ledger.itemmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_pending_receipts', to='stockops.location')),
            ],
            options={
                'verbose_name': 'Pending Receipt',
                'verbose_name_plural': 'Pending Receipts',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='stockops.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_transfers', to='django_ledger.itemmodel')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to', to='stockops.location')),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
            },
        ),
        migrations.CreateModel(
            name='StatusOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('in_transfer', 'In Transfer')], default='available', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('effective', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_status_overlays', to='django_ledger.itemmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_status_overlays', to='stockops.location')),
            ],
            options={
                'verbose_name': 'Status Overlay',
                'verbose_name_plural': 'Status Overlays',
                'unique_together': {('item', 'location', 'status', 'effective')},
            },
        ),
        migrations.CreateModel(
            name='StockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('in_transfer', 'In Transfer')], default='available', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_allocations', to='django_ledger.itemmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockops_allocations', to='stockops.location')),
            ],
            options={
                'verbose_name': 'Stock Allocation',
                'verbose_name_plural': 'Stock Allocations',
                'unique_together': {('item', 'location')},
            },
        ),
    ]
