# Generated by Django 5.2.5 on 2025-11-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0028_adminreports'),
        ('stockops', '0001_initial'),
    ]

    operations = [
        # DB: add the new FK, allow NULL for now
        migrations.AddField(
            model_name='location',
            name='entity',
            field=models.ForeignKey(
                to='django_ledger.entitymodel',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='locations',
                null=True,
                blank=True,
            ),
        ),
        # State-only correction for 'name' (so Django’s model state matches DB),
        # but DO NOT change the database (it already has a text column 'name').
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='location',
                    name='name',
                    field=models.CharField(max_length=140),
                ),
            ],
            database_operations=[],
        ),
    ]
     