# Generated by Django 5.2.5 on 2025-11-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0028_adminreports'),
        ('stockops', '0004_location_entity_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='django_ledger.entitymodel'),
        ),
    ]
