# Generated by Django 5.2.5 on 2025-11-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockops', '0005_alter_location_entity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockallocation',
            unique_together=set(),
        ),
    ]
