# Generated by Django 5.2.7 on 2025-12-04 22:19

import django.db.models.deletion
import django.utils.timezone
import forbes_lawn_billing.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0029_stagedtransactionmodel_matched_transaction_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(help_text='Visible invoice number (e.g. 492).', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=10)),
                ('terms', models.CharField(blank=True, help_text='e.g. Due on receipt, Net 30.', max_length=100)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('email_to', models.EmailField(blank=True, max_length=254)),
                ('email_cc', models.CharField(blank=True, max_length=255)),
                ('email_bcc', models.CharField(blank=True, max_length=255)),
                ('bill_to_name', models.CharField(blank=True, max_length=200)),
                ('bill_to_line1', models.CharField(blank=True, max_length=200)),
                ('bill_to_line2', models.CharField(blank=True, max_length=200)),
                ('bill_to_city', models.CharField(blank=True, max_length=100)),
                ('bill_to_state', models.CharField(blank=True, max_length=50)),
                ('bill_to_zip', models.CharField(blank=True, max_length=20)),
                ('bill_to_country', models.CharField(blank=True, max_length=100)),
                ('ship_to_name', models.CharField(blank=True, max_length=200)),
                ('ship_to_line1', models.CharField(blank=True, max_length=200)),
                ('ship_to_line2', models.CharField(blank=True, max_length=200)),
                ('ship_to_city', models.CharField(blank=True, max_length=100)),
                ('ship_to_state', models.CharField(blank=True, max_length=50)),
                ('ship_to_zip', models.CharField(blank=True, max_length=20)),
                ('ship_to_country', models.CharField(blank=True, max_length=100)),
                ('ship_from_name', models.CharField(blank=True, max_length=200)),
                ('ship_from_line1', models.CharField(blank=True, max_length=200)),
                ('ship_from_line2', models.CharField(blank=True, max_length=200)),
                ('ship_from_city', models.CharField(blank=True, max_length=100)),
                ('ship_from_state', models.CharField(blank=True, max_length=50)),
                ('ship_from_zip', models.CharField(blank=True, max_length=20)),
                ('ship_from_country', models.CharField(blank=True, max_length=100)),
                ('ship_via', models.CharField(blank=True, max_length=100)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags, replacing QB 'Tags (hidden)'.", max_length=255)),
                ('payment_instructions', models.TextField(blank=True, help_text='Customer payment options / how you want to be paid.')),
                ('note_to_customer', models.TextField(blank=True)),
                ('memo_on_statement', models.TextField(blank=True, help_text="Internal statement memo (won't show on invoice PDF).")),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate_name', models.CharField(blank=True, help_text="e.g. 'Automatic Calculation' or a named tax setup.", max_length=100)),
                ('tax_rate_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoice total before deposits/payments.', max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_in_full', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, help_text='Django Ledger entity this invoice belongs to (e.g. Forbes Lawn Spraying LLC).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forbes_lawn_invoices', to='django_ledger.entitymodel')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=forbes_lawn_billing.models.invoice_attachment_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forbes_lawn_billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(help_text='Product/Service name', max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxable', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='forbes_lawn_billing.invoice')),
            ],
            options={
                'ordering': ['line_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('ACH', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Check no., transaction id, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='forbes_lawn_billing.invoice')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
