# Generated by Django 5.2.7 on 2025-12-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbes_lawn_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='jobber_client_id',
            field=models.CharField(blank=True, help_text='Jobber client/customer ID.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='jobber_invoice_id',
            field=models.CharField(blank=True, help_text='Original Jobber invoice ID (for imports/sync).', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='jobber_property_id',
            field=models.CharField(blank=True, help_text='Jobber property/service location ID.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='jobber_line_id',
            field=models.CharField(blank=True, help_text='Jobber line item ID.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='jobber_service_id',
            field=models.CharField(blank=True, help_text='Jobber service/product ID.', max_length=64, null=True),
        ),
    ]
