# Generated by Django 5.2.5 on 2025-12-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbes_lawn_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(help_text='Display name for the customer at time of invoicing.', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='item_name',
            field=models.CharField(help_text='Product/Service name as shown on the invoice.', max_length=200),
        ),
    ]
