# Generated by Django 5.2.7 on 2025-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbes_lawn_billing', '0002_invoice_jobber_client_id_invoice_jobber_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='jobber_payment_id',
            field=models.CharField(blank=True, help_text='Unique payment ID from Jobber (for deduping imports).', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoicepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('jobber_payment_id__isnull', True), _negated=True), fields=('invoice', 'jobber_payment_id'), name='uniq_jobber_payment_per_invoice'),
        ),
    ]
