# Generated by Django 5.2.7 on 2025-12-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forbes_lawn_billing', '0003_invoicepayment_jobber_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_line1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_line2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_state',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_from_zip',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_country',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_line1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_line2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_state',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to_zip',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_via',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tracking_number',
        ),
    ]
