# Generated by Django 5.2.5 on 2025-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forbes_lawn_billing', '0003_rename_invoicepayment_date_to_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='jobber_job_numbers_raw',
            field=models.CharField(blank=True, default='', help_text="Raw Jobber Job #s from invoice export, e.g. '1219' or '1226,1225'.", max_length=255),
        ),
    ]
