# Generated by Django 5.2.5 on 2025-12-22 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        
    ]

    operations = [
        migrations.CreateModel(
            name='JobberPayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('balance_transaction_id', models.CharField(max_length=255)),
                ('txn_type', models.CharField(max_length=50)),
                ('gross_cents', models.IntegerField(blank=True, null=True)),
                ('fee_cents', models.IntegerField(blank=True, null=True)),
                ('net_cents', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('tip_cents', models.IntegerField(blank=True, null=True)),
                ('payment_record_id', models.CharField(blank=True, default='', max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobber_payout_transactions', to='django_ledger.entitymodel')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_transactions', to='jobber_sync.jobberpayment')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='jobber_sync.jobberpayout')),
            ],
            options={
                'indexes': [models.Index(fields=['entity', 'txn_type'], name='ix_jobber_payout_txn_type'), models.Index(fields=['created'], name='ix_jobber_payout_txn_created')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'balance_transaction_id'), name='uq_jobber_payout_txn_entity_balance_txn_id')],
            },
        ),
    ]
