# Generated by Django 5.2.5 on 2025-12-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber_sync', '0003_jobberoauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=50)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobberOAuthToken',
        ),
    ]
