# Generated by Django 5.2.5 on 2025-12-21 23:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='JobberClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jobber_id', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('bill_to_line1', models.CharField(blank=True, default='', max_length=255)),
                ('bill_to_line2', models.CharField(blank=True, default='', max_length=255)),
                ('bill_to_city', models.CharField(blank=True, default='', max_length=100)),
                ('bill_to_state', models.CharField(blank=True, default='', max_length=50)),
                ('bill_to_zip', models.CharField(blank=True, default='', max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobber_clients', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobberInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jobber_id', models.CharField(max_length=64)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client_jobber_id', models.CharField(blank=True, default='', max_length=64)),
                ('property_jobber_id', models.CharField(blank=True, default='', max_length=64)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tip_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_rate_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='jobber_sync.jobberclient')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobber_invoices', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jobber_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category_jobber_id', models.CharField(blank=True, default='', max_length=64)),
                ('category_name', models.CharField(blank=True, default='', max_length=255)),
                ('taxable_default', models.BooleanField(default=False)),
                ('default_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('internal_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('visibility', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobber_items', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobberInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jobber_line_id', models.CharField(max_length=64)),
                ('item_jobber_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxable', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='jobber_sync.jobberinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='jobber_sync.jobberitem')),
            ],
        ),
        migrations.CreateModel(
            name='JobberPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jobber_id', models.CharField(max_length=64)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=100)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_jobber_id', models.CharField(blank=True, default='', max_length=64)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobber_payments', to='django_ledger.entitymodel')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='jobber_sync.jobberinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='JobberPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jobber_id', models.CharField(max_length=64)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobber_payouts', to='django_ledger.entitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='JobberPayoutPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payouts', to='jobber_sync.jobberpayment')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_payments', to='jobber_sync.jobberpayout')),
            ],
        ),
        migrations.AddIndex(
            model_name='jobberclient',
            index=models.Index(fields=['entity', 'display_name'], name='ix_jobber_client_name'),
        ),
        migrations.AddConstraint(
            model_name='jobberclient',
            constraint=models.UniqueConstraint(fields=('entity', 'jobber_id'), name='uq_jobber_client_entity_jobber_id'),
        ),
        migrations.AddIndex(
            model_name='jobberinvoice',
            index=models.Index(fields=['entity', 'issued_date'], name='ix_jobber_invoice_issued'),
        ),
        migrations.AddIndex(
            model_name='jobberinvoice',
            index=models.Index(fields=['entity', 'status'], name='ix_jobber_invoice_status'),
        ),
        migrations.AddIndex(
            model_name='jobberinvoice',
            index=models.Index(fields=['entity', 'invoice_number'], name='ix_jobber_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='jobberinvoice',
            constraint=models.UniqueConstraint(fields=('entity', 'jobber_id'), name='uq_jobber_invoice_entity_jobber_id'),
        ),
        migrations.AddIndex(
            model_name='jobberitem',
            index=models.Index(fields=['entity', 'name'], name='ix_jobber_item_name'),
        ),
        migrations.AddConstraint(
            model_name='jobberitem',
            constraint=models.UniqueConstraint(fields=('entity', 'jobber_id'), name='uq_jobber_item_entity_jobber_id'),
        ),
        migrations.AddIndex(
            model_name='jobberinvoiceline',
            index=models.Index(fields=['invoice', 'name'], name='ix_jobber_invline_name'),
        ),
        migrations.AddConstraint(
            model_name='jobberinvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'jobber_line_id'), name='uq_jobber_invoice_line_invoice_jobber_line_id'),
        ),
        migrations.AddIndex(
            model_name='jobberpayment',
            index=models.Index(fields=['entity', 'payment_date'], name='ix_jobber_payment_date'),
        ),
        migrations.AddConstraint(
            model_name='jobberpayment',
            constraint=models.UniqueConstraint(fields=('entity', 'jobber_id'), name='uq_jobber_payment_entity_jobber_id'),
        ),
        migrations.AddIndex(
            model_name='jobberpayout',
            index=models.Index(fields=['entity', 'payout_date'], name='ix_jobber_payout_date'),
        ),
        migrations.AddConstraint(
            model_name='jobberpayout',
            constraint=models.UniqueConstraint(fields=('entity', 'jobber_id'), name='uq_jobber_payout_entity_jobber_id'),
        ),
        migrations.AddConstraint(
            model_name='jobberpayoutpayment',
            constraint=models.UniqueConstraint(fields=('payout', 'payment'), name='uq_jobber_payout_payment_pair'),
        ),
    ]
